// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3MAk_mdaUaRA2vDUJdei0NB8mrEeRD8Y',
    appId: '1:4373122723:web:d9e3937483f116bb8ab916',
    messagingSenderId: '4373122723',
    projectId: 'bantubangkit-52722',
    authDomain: 'bantubangkit-52722.firebaseapp.com',
    storageBucket: 'bantubangkit-52722.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3zvg3Z3tnvQfliuQ1TscyrggEwjeu1qI',
    appId: '1:4373122723:android:372cb55715a77f1a8ab916',
    messagingSenderId: '4373122723',
    projectId: 'bantubangkit-52722',
    storageBucket: 'bantubangkit-52722.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdqKCs1yl5lfL87jioIAhxXadOtU8hEp0',
    appId: '1:4373122723:ios:85cc62a013e40b378ab916',
    messagingSenderId: '4373122723',
    projectId: 'bantubangkit-52722',
    storageBucket: 'bantubangkit-52722.appspot.com',
    iosBundleId: 'com.example.linens',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdqKCs1yl5lfL87jioIAhxXadOtU8hEp0',
    appId: '1:4373122723:ios:39fd4c497d1a6bcd8ab916',
    messagingSenderId: '4373122723',
    projectId: 'bantubangkit-52722',
    storageBucket: 'bantubangkit-52722.appspot.com',
    iosBundleId: 'com.example.linens.RunnerTests',
  );
}
